name: "Spec Gardener"
description: "Turn vague ideas into code-ready specifications via AI CLI tools."
author: "ponharu"

inputs:
  agent:
    description: "CLI agent command (codex, claude, gemini)"
    required: true
  github_token:
    description: "GitHub token for API access"
    required: true
  agent_timeout_ms:
    description: "Timeout in milliseconds for the agent execution"
    required: false
    default: "120000"
  custom_prompt:
    description: "Custom instructions to append to the prompt"
    required: false
  mention_on:
    description: "Comma-separated list of outcomes that should mention the issue author (question, complete, error)"
    required: false
    default: "question,complete,error"
runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun install --production
    - name: Run Spec Gardener
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run src/index.ts
      env:
        INPUT_AGENT: ${{ inputs.agent }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_AGENT_TIMEOUT_MS: ${{ inputs.agent_timeout_ms }}
        INPUT_CUSTOM_PROMPT: ${{ inputs.custom_prompt }}
        INPUT_MENTION_ON: ${{ inputs.mention_on }}
