import { COMMAND_PATTERN, FOOTER } from "./constants";

export type CommentCommand = "continue" | "reset" | "help";

export type EventPayload = {
  issue?: { number?: number; body?: string; pull_request?: object };
  pull_request?: { number?: number; body?: string };
  comment?: { body?: string; created_at?: string };
};

export const hasFooter = (text: string): boolean => text.includes(FOOTER);

export const parseCommand = (text: string): CommentCommand | null => {
  const match = COMMAND_PATTERN.exec(text);
  if (!match) {
    return null;
  }
  const subcommand = match[1]?.toLowerCase();
  switch (subcommand) {
    case "reset":
      return "reset";
    case "help":
      return "help";
    default:
      return "continue";
  }
};

export const shouldProcess = (
  eventName: string,
  event: EventPayload,
): {
  shouldRun: boolean;
  reason?: string;
  command?: CommentCommand;
  commandCreatedAt?: string;
} => {
  if (eventName === "issue_comment") {
    const commentBody = event.comment?.body ?? "";
    if (hasFooter(commentBody)) {
      return {
        shouldRun: false,
        reason: "Skipping: comment generated by Spec Gardener.",
      };
    }
    const command = parseCommand(commentBody);
    if (!command) {
      return {
        shouldRun: false,
        reason: "Skipping: comment does not contain /spec-gardener command.",
      };
    }
    return {
      shouldRun: true,
      command,
      commandCreatedAt: event.comment?.created_at,
    };
  }

  if (eventName === "pull_request") {
    const pullBody = event.pull_request?.body ?? "";
    if (hasFooter(pullBody)) {
      return {
        shouldRun: false,
        reason: "Skipping: pull request body already contains Spec Gardener footer.",
      };
    }
    return { shouldRun: true };
  }

  // For issues events (opened, edited, labeled, etc.)
  const issueBody = event.issue?.body ?? "";
  if (hasFooter(issueBody)) {
    return {
      shouldRun: false,
      reason: "Skipping: issue body already contains Spec Gardener footer.",
    };
  }

  return { shouldRun: true };
};
