export const FOOTER = "🤖 Generated by Spec Gardener";
export const COMMAND_PATTERN = /\/spec-gardener(?:\s+(reset|help))?\b/i;
export const DEFAULT_AGENT_TIMEOUT_MS = 120000;
export const THUMBS_UP_REACTION = "+1";

export const COMMANDS_HINT = "💡 Type `/spec-gardener help` for available commands";

export const COMMANDS_LIST = [
  "- `/spec-gardener` - Continue the conversation to refine this specification",
  "- `/spec-gardener reset` - Re-analyze from the original description and comments from the reset point onward",
  "- `/spec-gardener help` - Show available commands",
].join("\n");
